### ISSUE TITLE
purpose of this dist?

### ISSUE THREAD

**Issue by karenetheridge** [Csson/p5-Dist-Iller#1]
I think you should consider either moving this dist/command into an author-specific repo, or delete it entirely...  you say:

> The reason for not just releasing the plugin bundles is the iller command. Together with the profile it initializes a git repository, runs dzil build on it, and then adds the newly created files to the repo. I find that useful.

...but all these things can already be accomplished directly in a minting profile.  e.g. mine creates the github repository, initializes the local git repo, commits the initial files, etc.:

https://github.com/karenetheridge/Dist-Zilla-PluginBundle-Author-ETHER/blob/master/share/profiles/github/profile.ini

**Comment by Csson** [comment]
Hi!

No problem. I have released the plugin bundles separately (under ::Author::CSSON), released Dist::Iller with it marked deprecated, and I'll delete all its files on Pause later.
